### ISSUE TITLE
Does not work with Ruby 2.6.6, bundler 2.1.4

### ISSUE THREAD

**Issue by morgoth** [sinsoku/bundler_diffgems#10]
Not sure which update caused problems, but with this combination it outputs:
```
bundle diff
ERROR: gem name required
```

**Comment by fujimura** [comment]
This seems to be happened because of the gem you'd installed was https://github.com/readysteady/bundle-diff, not this gem. I've faced the same but just uninstalling readysteady/bundle-diff fixed the problem.

**Comment by morgoth** [comment]
Indeed. Thank you.
